### ISSUE TITLE
Error when trying to get a Layer to versioning

### ISSUE THREAD

**Issue by NapoProg** [sourcepole/pgversion#4]
![pgversionfehler](https://user-images.githubusercontent.com/32090200/30580749-f38e4cce-9d1d-11e7-9c44-1ca21b13927e.JPG)
This Error always occurs when i try to add a Layer to versioning. I'm sorry for the german language, i set QGIS to English but the message still in german.

**Comment by NapoProg** [comment]
Could solve the Problem by outcommentig the Statement (I think it doesnt select into anything)
Now it works so far but i get another error
If I try to load a versioned layer i can choose it but nothing happens.

**Comment by hdus** [comment]
I have pushed fixed create and update sql scripts. please give it a try and let me know if it works.

**Comment by NapoProg** [comment]
Still the same situation. Initializes successful and the table appears in the "versions"-Schema, but if I want to load the Layer nothing happens.

**Comment by hdus** [comment]
Please add the corresponding layer to the database group "versions". Than it should work. I have commited a fix.
